// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.
//
// Copyright (c) 2026 Torlando Tech LLC

//
//  IFACInteropTests.swift
//  ReticulumSwift
//
//  E2E interop tests for IFAC (Interface Access Code) validation.
//  Test vectors generated by Python RNS reference implementation.
//

import XCTest
@testable import ReticulumSwift

final class IFACInteropTests: XCTestCase {

    // MARK: - Test Vectors (generated by Python RNS)

    /// 64-byte IFAC key (first 32 = X25519, last 32 = Ed25519 private)
    let ifacKeyHex = "000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f202122232425262728292a2b2c2d2e2f303132333435363738393a3b3c3d3e3f"

    /// Original unprotected packet (29 bytes)
    let originalPacketHex = "00004142434445464748494a4b4c4d4e4f5048656c6c6f20576f726c64"

    /// Masked packet with IFAC applied by Python (45 bytes)
    let maskedPacketHex = "c4d82760baa6cb905b3519cb1013226e2c08a8bf46141229e96415718c8e94dcd7892f8a271b1070322a413eb2"

    let ifacSize = 16

    // MARK: - Helpers

    private func hexToData(_ hex: String) -> Data {
        var data = Data()
        var index = hex.startIndex
        while index < hex.endIndex {
            let nextIndex = hex.index(index, offsetBy: 2)
            let byteString = hex[index..<nextIndex]
            data.append(UInt8(byteString, radix: 16)!)
            index = nextIndex
        }
        return data
    }

    /// Create a transport with a mock interface that has IFAC configured.
    private func makeTransportWithIFAC() async throws -> (ReticulumTransport, String) {
        let ifacKey = hexToData(ifacKeyHex)
        let interfaceId = "ifac-test-interface"

        let config = InterfaceConfig(
            id: interfaceId,
            name: "IFAC Test",
            type: .tcp,
            enabled: true,
            mode: .full,
            host: "127.0.0.1",
            port: 0,
            ifac: nil,
            announceRateTarget: nil,
            announceRateGrace: 0,
            announceRatePenalty: 0,
            bitrate: 0,
            ifacSize: ifacSize,
            ifacKey: ifacKey
        )

        let transport = ReticulumTransport()
        let mock = MockIFACInterface(config: config)
        // addInterface will connect (no-op), derive IFAC identity, and register
        try await transport.addInterface(mock)

        return (transport, interfaceId)
    }

    // MARK: - Ed25519 Determinism Test

    /// Verify that Ed25519Pure produces the same signature as Python.
    func testEd25519PureMatchesPython() {
        let seed = hexToData("202122232425262728292a2b2c2d2e2f303132333435363738393a3b3c3d3e3f")
        let message = hexToData(originalPacketHex)
        let expectedSig = hexToData("f9952f95c5b721882566af01a25003c60d7a17243f2381a9beeb318b1b5c365edcd955b26526e568ad743079ec5a5f502760baa6cb905b3519cb1013226e2c08")

        let sig = Ed25519Pure.sign(message: message, seed: seed)
        XCTAssertNotNil(sig, "Ed25519Pure.sign should succeed")
        XCTAssertEqual(sig, expectedSig, "Ed25519Pure signature should match Python byte-for-byte")
    }

    /// Verify Ed25519Pure is deterministic (same key+message = same signature).
    func testEd25519PureDeterministic() {
        let seed = hexToData("202122232425262728292a2b2c2d2e2f303132333435363738393a3b3c3d3e3f")
        let message = hexToData(originalPacketHex)

        let sig1 = Ed25519Pure.sign(message: message, seed: seed)
        let sig2 = Ed25519Pure.sign(message: message, seed: seed)
        XCTAssertEqual(sig1, sig2, "Ed25519Pure should produce deterministic signatures")
    }

    // MARK: - Validation Tests

    /// Test that Swift can validate a packet masked by Python RNS.
    func testValidatePythonMaskedPacket() async throws {
        let (transport, interfaceId) = try await makeTransportWithIFAC()
        let maskedPacket = hexToData(maskedPacketHex)
        let expectedOriginal = hexToData(originalPacketHex)

        let result = await transport.validateIFAC(raw: maskedPacket, interfaceId: interfaceId)

        XCTAssertNotNil(result, "IFAC validation should succeed for Python-masked packet")
        XCTAssertEqual(result, expectedOriginal, "Validated packet should match original")
    }

    /// Test that Swift apply then validate round-trips correctly.
    func testApplyThenValidateRoundTrip() async throws {
        let (transport, interfaceId) = try await makeTransportWithIFAC()
        let original = hexToData(originalPacketHex)

        // Apply IFAC
        let masked = await transport.applyIFAC(raw: original, interfaceId: interfaceId)
        XCTAssertNotEqual(masked, original, "Masked packet should differ from original")
        XCTAssertEqual(masked.count, original.count + ifacSize, "Masked should be ifacSize bytes longer")

        // IFAC flag should be set
        XCTAssertTrue(masked[0] & 0x80 == 0x80, "IFAC flag should be set")

        // Validate (unmask)
        let restored = await transport.validateIFAC(raw: masked, interfaceId: interfaceId)
        XCTAssertNotNil(restored, "Round-trip validation should succeed")
        XCTAssertEqual(restored, original, "Restored should match original")
    }

    /// Test that Swift-masked packet matches Python-masked packet byte-for-byte.
    func testSwiftMaskedMatchesPython() async throws {
        let (transport, interfaceId) = try await makeTransportWithIFAC()
        let original = hexToData(originalPacketHex)
        let expectedMasked = hexToData(maskedPacketHex)

        let swiftMasked = await transport.applyIFAC(raw: original, interfaceId: interfaceId)

        // Ed25519 signatures are deterministic, so output should be identical
        XCTAssertEqual(swiftMasked, expectedMasked,
                       "Swift IFAC output should match Python byte-for-byte")
    }

    /// Test that a tampered packet fails validation.
    func testTamperedPacketRejected() async throws {
        let (transport, interfaceId) = try await makeTransportWithIFAC()
        var maskedPacket = hexToData(maskedPacketHex)

        // Tamper with a payload byte
        maskedPacket[maskedPacket.count - 1] ^= 0xFF

        let result = await transport.validateIFAC(raw: maskedPacket, interfaceId: interfaceId)
        XCTAssertNil(result, "Tampered packet should fail IFAC validation")
    }

    /// Test that a packet without IFAC flag is rejected when interface requires IFAC.
    func testNoIFACFlagRejectedWhenRequired() async throws {
        let (transport, interfaceId) = try await makeTransportWithIFAC()
        let plainPacket = hexToData(originalPacketHex)

        // Original packet has no IFAC flag (bit 7 = 0)
        XCTAssertTrue(plainPacket[0] & 0x80 == 0x00, "Test packet should not have IFAC flag")

        let result = await transport.validateIFAC(raw: plainPacket, interfaceId: interfaceId)
        XCTAssertNil(result, "Packet without IFAC flag should be rejected when interface requires IFAC")
    }

    /// Test that IFAC flag packet is rejected on interface without IFAC.
    func testIFACFlagRejectedWhenNotConfigured() async throws {
        let transport = ReticulumTransport()
        let noIfacConfig = InterfaceConfig(
            id: "no-ifac",
            name: "No IFAC",
            type: .tcp,
            enabled: true,
            mode: .full,
            host: "127.0.0.1",
            port: 0
        )
        let mock = MockIFACInterface(config: noIfacConfig)
        try await transport.addInterface(mock)

        // Create a packet with IFAC flag set
        var packetWithFlag = hexToData(originalPacketHex)
        packetWithFlag[0] |= 0x80

        let result = await transport.validateIFAC(raw: packetWithFlag, interfaceId: "no-ifac")
        XCTAssertNil(result, "Packet with IFAC flag should be rejected on interface without IFAC")
    }

    /// Test that no-IFAC passthrough works for normal packets on unconfigured interfaces.
    func testNoIFACPassthrough() async throws {
        let transport = ReticulumTransport()
        let noIfacConfig = InterfaceConfig(
            id: "no-ifac",
            name: "No IFAC",
            type: .tcp,
            enabled: true,
            mode: .full,
            host: "127.0.0.1",
            port: 0
        )
        let mock = MockIFACInterface(config: noIfacConfig)
        try await transport.addInterface(mock)

        let plainPacket = hexToData(originalPacketHex)
        let result = await transport.validateIFAC(raw: plainPacket, interfaceId: "no-ifac")
        XCTAssertEqual(result, plainPacket, "Plain packet should pass through on interface without IFAC")
    }

    /// Test applyIFAC is no-op on interface without IFAC.
    func testApplyIFACNoopWithoutConfig() async throws {
        let transport = ReticulumTransport()
        let noIfacConfig = InterfaceConfig(
            id: "no-ifac",
            name: "No IFAC",
            type: .tcp,
            enabled: true,
            mode: .full,
            host: "127.0.0.1",
            port: 0
        )
        let mock = MockIFACInterface(config: noIfacConfig)
        try await transport.addInterface(mock)

        let original = hexToData(originalPacketHex)
        let result = await transport.applyIFAC(raw: original, interfaceId: "no-ifac")
        XCTAssertEqual(result, original, "applyIFAC should be no-op without IFAC config")
    }

    /// Test with wrong key fails validation.
    func testWrongKeyFails() async throws {
        let (transport, _) = try await makeTransportWithIFAC()

        // Add a second interface with different key
        let wrongKey = Data(repeating: 0xFF, count: 64)
        let wrongConfig = InterfaceConfig(
            id: "wrong-key",
            name: "Wrong Key",
            type: .tcp,
            enabled: true,
            mode: .full,
            host: "127.0.0.1",
            port: 0,
            ifac: nil,
            announceRateTarget: nil,
            announceRateGrace: 0,
            announceRatePenalty: 0,
            bitrate: 0,
            ifacSize: ifacSize,
            ifacKey: wrongKey
        )
        let wrongMock = MockIFACInterface(config: wrongConfig)
        try await transport.addInterface(wrongMock)

        // Masked by correct key
        let maskedPacket = hexToData(maskedPacketHex)

        // Try to validate with wrong key
        let result = await transport.validateIFAC(raw: maskedPacket, interfaceId: "wrong-key")
        XCTAssertNil(result, "Packet masked with different key should fail validation")
    }
}

// MARK: - Mock Interface

/// Minimal mock interface for IFAC testing (no real connection needed).
actor MockIFACInterface: NetworkInterface {
    let id: String
    let config: InterfaceConfig
    nonisolated var state: InterfaceState { .connected }

    init(config: InterfaceConfig) {
        self.id = config.id
        self.config = config
    }

    func connect() async throws {}
    func disconnect() async {}
    func send(_ data: Data) async throws {}
    func setDelegate(_ delegate: any InterfaceDelegate) {}
}
