// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.
//
// Copyright (c) 2026 Torlando Tech LLC

//
//  RoutingInteropTests.swift
//  ReticulumSwift
//
//  E2E interop tests for routing: packet rewriting, link ID computation,
//  reverse table keying, multi-hop relay chains, and timeout constants.
//
//  Test vectors generated by Python generate_routing_vectors.py which
//  implements the same algorithms as Python RNS Transport.py and Packet.py.
//

import XCTest
@testable import ReticulumSwift

final class RoutingInteropTests: XCTestCase {

    // MARK: - Helpers

    private func hex(_ s: String) -> Data {
        var data = Data()
        var index = s.startIndex
        while index < s.endIndex {
            let next = s.index(index, offsetBy: 2)
            data.append(UInt8(s[index..<next], radix: 16)!)
            index = next
        }
        return data
    }

    private func hexString(_ d: Data) -> String {
        d.map { String(format: "%02x", $0) }.joined()
    }

    // MARK: - Common test data

    /// 16-byte destination hash
    private var destHash: Data { hex("a0a1a2a3a4a5a6a7a8a9aaabacadaeaf") }
    /// 16-byte incoming transport address
    private var transportAddrIn: Data { hex("b0b1b2b3b4b5b6b7b8b9babbbcbdbebf") }
    /// 16-byte next hop transport address
    private var nextHop: Data { hex("c0c1c2c3c4c5c6c7c8c9cacbcccdcecf") }
    /// 67-byte LINKREQUEST data (enc_pub + sig_pub + signaling)
    private var lrData: Data {
        hex("505152535455565758595a5b5c5d5e5f606162636465666768696a6b6c6d6e6f" +
            "707172737475767778797a7b7c7d7e7f808182838485868788898a8b8c8d8e8f" +
            "2001f4")
    }
    /// Expected link_id (from Python)
    private var expectedLinkId: Data { hex("82c79bf92ef8225a4bcdf4b6995fdf90") }

    // MARK: - 1. HEADER_2 → HEADER_2 Rewrite

    /// Verify that rewriting a HEADER_2 packet with new transport address and hops
    /// produces byte-identical output to Python.
    func testH2ToH2RewriteMatchesPython() {
        let expectedForwarded = hex(
            "5203c0c1c2c3c4c5c6c7c8c9cacbcccdcecf" +
            "a0a1a2a3a4a5a6a7a8a9aaabacadaeaf00" +
            "505152535455565758595a5b5c5d5e5f606162636465666768696a6b6c6d6e6f" +
            "707172737475767778797a7b7c7d7e7f808182838485868788898a8b8c8d8e8f" +
            "2001f4"
        )

        // Build incoming H2 LINKREQUEST
        let incomingHeader = PacketHeader(
            headerType: .header2,
            hasContext: false,
            transportType: .transport,
            destinationType: .single,
            packetType: .linkRequest,
            hopCount: 2
        )
        let incoming = Packet(
            header: incomingHeader,
            destination: destHash,
            transportAddress: transportAddrIn,
            context: 0x00,
            data: lrData
        )

        // Rewrite as H2 with new transport and incremented hops (matches rewriteAsHeader2)
        let newHeader = PacketHeader(
            headerType: .header2,
            hasContext: false,
            transportType: .transport,
            destinationType: incoming.header.destinationType,
            packetType: incoming.header.packetType,
            hopCount: 3  // incremented
        )
        let forwarded = Packet(
            header: newHeader,
            destination: incoming.destination,
            transportAddress: nextHop,
            context: incoming.context,
            data: incoming.data
        )

        XCTAssertEqual(forwarded.encode(), expectedForwarded,
                       "H2→H2 rewrite should match Python byte-for-byte")
    }

    // MARK: - 2. HEADER_2 → HEADER_1 Rewrite (last hop)

    /// Verify that converting HEADER_2 to HEADER_1 (strip transport address) matches Python.
    func testH2ToH1RewriteMatchesPython() {
        let expectedForwarded = hex(
            "0203" +
            "a0a1a2a3a4a5a6a7a8a9aaabacadaeaf00" +
            "505152535455565758595a5b5c5d5e5f606162636465666768696a6b6c6d6e6f" +
            "707172737475767778797a7b7c7d7e7f808182838485868788898a8b8c8d8e8f" +
            "2001f4"
        )

        let incoming = Packet(
            header: PacketHeader(
                headerType: .header2,
                hasContext: false,
                transportType: .transport,
                destinationType: .single,
                packetType: .linkRequest,
                hopCount: 2
            ),
            destination: destHash,
            transportAddress: transportAddrIn,
            context: 0x00,
            data: lrData
        )

        // Rewrite as H1 (strip transport address, set broadcast)
        let h1Header = PacketHeader(
            headerType: .header1,
            hasContext: false,
            transportType: .broadcast,
            destinationType: incoming.header.destinationType,
            packetType: incoming.header.packetType,
            hopCount: 3
        )
        let forwarded = Packet(
            header: h1Header,
            destination: incoming.destination,
            transportAddress: nil,
            context: incoming.context,
            data: incoming.data
        )

        XCTAssertEqual(forwarded.encode(), expectedForwarded,
                       "H2→H1 rewrite should match Python byte-for-byte")
    }

    // MARK: - 3. Hop Count Byte Position

    /// Verify that hop count is always at byte[1] and only byte[1] changes.
    func testHopCountRewriteBytePosition() {
        let original = hex(
            "0f05a0a1a2a3a4a5a6a7a8a9aaabacadaeaf00" +
            "101112131415161718191a1b1c1d1e1f202122232425262728292a2b2c2d2e2f" +
            "303132333435363738393a3b3c3d3e3f404142434445464748494a4b4c4d4e4f" +
            "505152535455565758595a5b5c5d5e5f606162636465666768696a6b6c6d6e6f" +
            "70717273"
        )
        let expected = hex(
            "0f06a0a1a2a3a4a5a6a7a8a9aaabacadaeaf00" +
            "101112131415161718191a1b1c1d1e1f202122232425262728292a2b2c2d2e2f" +
            "303132333435363738393a3b3c3d3e3f404142434445464748494a4b4c4d4e4f" +
            "505152535455565758595a5b5c5d5e5f606162636465666768696a6b6c6d6e6f" +
            "70717273"
        )

        // Simulate rewriteHopCount
        var modified = original
        modified[1] = 6
        XCTAssertEqual(modified, expected, "Only byte[1] should change during hop rewrite")

        // Verify byte[0] unchanged
        XCTAssertEqual(original[0], modified[0])
        // Verify all bytes after [1] unchanged
        XCTAssertEqual(original[2...], modified[2...])
    }

    // MARK: - 4. Reverse Table Key Computation

    /// Verify that the reverse table key (truncated hash of DATA packet) matches Python.
    func testReverseTableKeyMatchesPython() {
        let expectedKey = hex("e59bcd4453f2028357b34a11af583bb3")
        let dataPayload = "Hello routing test!".data(using: .utf8)!

        // Build H2 DATA packet
        let dataPacket = Packet(
            header: PacketHeader(
                headerType: .header2,
                hasContext: false,
                transportType: .transport,
                destinationType: .single,
                packetType: .data,
                hopCount: 1
            ),
            destination: destHash,
            transportAddress: transportAddrIn,
            context: 0x00,
            data: dataPayload
        )

        // Verify raw encoding matches Python
        let expectedRaw = hex(
            "5001b0b1b2b3b4b5b6b7b8b9babbbcbdbebf" +
            "a0a1a2a3a4a5a6a7a8a9aaabacadaeaf00" +
            "48656c6c6f20726f7574696e67207465737421"
        )
        XCTAssertEqual(dataPacket.encode(), expectedRaw, "DATA packet encoding should match Python")

        // Verify hashable part
        let expectedHashable = hex(
            "00a0a1a2a3a4a5a6a7a8a9aaabacadaeaf00" +
            "48656c6c6f20726f7574696e67207465737421"
        )
        XCTAssertEqual(dataPacket.getHashablePart(), expectedHashable,
                       "H2 hashable part should skip transport address")

        // Verify truncated hash (reverse table key)
        let reverseKey = dataPacket.getTruncatedHash()
        XCTAssertEqual(reverseKey, expectedKey,
                       "Reverse table key should match Python SHA256(hashable)[:16]")
    }

    // MARK: - 5. Link ID Hop Independence

    /// Verify that the same LINKREQUEST produces the same link_id regardless of hop count.
    func testLinkIdHopIndependent() {
        for hops: UInt8 in [0, 1, 5, 128, 255] {
            let packet = Packet(
                header: PacketHeader(
                    headerType: .header1,
                    hasContext: false,
                    transportType: .broadcast,
                    destinationType: .single,
                    packetType: .linkRequest,
                    hopCount: hops
                ),
                destination: destHash,
                context: 0x00,
                data: lrData
            )

            var hashable = packet.getHashablePart()
            // Trim signaling (67 - 64 = 3 bytes)
            let ecPubSize = 64
            if lrData.count > ecPubSize {
                hashable = Data(hashable.dropLast(lrData.count - ecPubSize))
            }
            let linkId = Hashing.truncatedHash(hashable)

            XCTAssertEqual(linkId, expectedLinkId,
                           "Link ID should be hop-independent (hops=\(hops))")
        }
    }

    /// Verify that link_id is transport-address-independent for HEADER_2 packets.
    func testLinkIdTransportAddrIndependent() {
        for taByte: UInt8 in [0x00, 0x55, 0xFF] {
            let ta = Data(repeating: taByte, count: 16)
            let packet = Packet(
                header: PacketHeader(
                    headerType: .header2,
                    hasContext: false,
                    transportType: .transport,
                    destinationType: .single,
                    packetType: .linkRequest,
                    hopCount: 1
                ),
                destination: destHash,
                transportAddress: ta,
                context: 0x00,
                data: lrData
            )

            var hashable = packet.getHashablePart()
            let ecPubSize = 64
            if lrData.count > ecPubSize {
                hashable = Data(hashable.dropLast(lrData.count - ecPubSize))
            }
            let linkId = Hashing.truncatedHash(hashable)

            XCTAssertEqual(linkId, expectedLinkId,
                           "Link ID should be transport-addr-independent (ta=0x\(String(format: "%02x", taByte)))")
        }
    }

    /// Verify link_id computed from H1 equals link_id computed from H2.
    func testLinkIdSameForH1AndH2() {
        let h1Packet = Packet(
            header: PacketHeader(
                headerType: .header1,
                hasContext: false,
                transportType: .broadcast,
                destinationType: .single,
                packetType: .linkRequest,
                hopCount: 0
            ),
            destination: destHash,
            context: 0x00,
            data: lrData
        )
        let h2Packet = Packet(
            header: PacketHeader(
                headerType: .header2,
                hasContext: false,
                transportType: .transport,
                destinationType: .single,
                packetType: .linkRequest,
                hopCount: 3
            ),
            destination: destHash,
            transportAddress: transportAddrIn,
            context: 0x00,
            data: lrData
        )

        func computeLinkId(_ pkt: Packet) -> Data {
            var hashable = pkt.getHashablePart()
            if pkt.data.count > 64 {
                hashable = Data(hashable.dropLast(pkt.data.count - 64))
            }
            return Hashing.truncatedHash(hashable)
        }

        let h1LinkId = computeLinkId(h1Packet)
        let h2LinkId = computeLinkId(h2Packet)
        XCTAssertEqual(h1LinkId, h2LinkId, "Link ID from H1 must equal link ID from H2")
        XCTAssertEqual(h1LinkId, expectedLinkId, "Link ID should match Python")
    }

    // MARK: - 6. Multi-Hop Relay Chain

    /// Verify that a LINKREQUEST packet rewritten at each hop in a 3-hop chain
    /// produces the expected bytes and maintains a stable link_id.
    func testRelayChainBytesMatchPython() {
        let nodeC = Data(repeating: 0xCC, count: 16)

        // A sends H1, hops=0
        let initialH1 = Packet(
            header: PacketHeader(
                headerType: .header1, hasContext: false,
                transportType: .broadcast, destinationType: .single,
                packetType: .linkRequest, hopCount: 0
            ),
            destination: destHash, context: 0x00, data: lrData
        )
        let expectedInitial = hex(
            "0200a0a1a2a3a4a5a6a7a8a9aaabacadaeaf00" +
            "505152535455565758595a5b5c5d5e5f606162636465666768696a6b6c6d6e6f" +
            "707172737475767778797a7b7c7d7e7f808182838485868788898a8b8c8d8e8f" +
            "2001f4"
        )
        XCTAssertEqual(initialH1.encode(), expectedInitial, "A's initial H1 should match Python")

        // B receives, converts to H2 with node_c as transport, hops=1
        let atB = Packet(
            header: PacketHeader(
                headerType: .header2, hasContext: false,
                transportType: .transport, destinationType: .single,
                packetType: .linkRequest, hopCount: 1
            ),
            destination: destHash, transportAddress: nodeC, context: 0x00, data: lrData
        )
        let expectedAtB = hex(
            "5201cccccccccccccccccccccccccccccccca0a1a2a3a4a5a6a7a8a9aaabacadaeaf00" +
            "505152535455565758595a5b5c5d5e5f606162636465666768696a6b6c6d6e6f" +
            "707172737475767778797a7b7c7d7e7f808182838485868788898a8b8c8d8e8f" +
            "2001f4"
        )
        XCTAssertEqual(atB.encode(), expectedAtB, "B's H2 forward should match Python")

        // C receives, converts to H1 (last hop), hops=2
        let atC = Packet(
            header: PacketHeader(
                headerType: .header1, hasContext: false,
                transportType: .broadcast, destinationType: .single,
                packetType: .linkRequest, hopCount: 2
            ),
            destination: destHash, context: 0x00, data: lrData
        )
        let expectedAtC = hex(
            "0202a0a1a2a3a4a5a6a7a8a9aaabacadaeaf00" +
            "505152535455565758595a5b5c5d5e5f606162636465666768696a6b6c6d6e6f" +
            "707172737475767778797a7b7c7d7e7f808182838485868788898a8b8c8d8e8f" +
            "2001f4"
        )
        XCTAssertEqual(atC.encode(), expectedAtC, "C's H1 forward should match Python")

        // All three should produce the same link_id
        func computeLinkId(_ pkt: Packet) -> Data {
            var hashable = pkt.getHashablePart()
            if pkt.data.count > 64 {
                hashable = Data(hashable.dropLast(pkt.data.count - 64))
            }
            return Hashing.truncatedHash(hashable)
        }

        let lidA = computeLinkId(initialH1)
        let lidB = computeLinkId(atB)
        let lidC = computeLinkId(atC)

        XCTAssertEqual(lidA, lidB, "Link ID at A must equal link ID at B")
        XCTAssertEqual(lidB, lidC, "Link ID at B must equal link ID at C")
        XCTAssertEqual(lidA, expectedLinkId, "Link ID should match Python across entire chain")
    }

    // MARK: - 7. Max Hops Enforcement

    /// Verify PATHFINDER_M constant matches Python.
    func testPathfinderMConstant() {
        XCTAssertEqual(TransportConstants.PATHFINDER_M, 128,
                       "PATHFINDER_M should be 128 (matching Python)")
    }

    /// Verify that packet at PATHFINDER_M hops is dropped (hops+1 > M).
    func testMaxHopsDropped() async throws {
        let (transport, _, interfaceB, destHash, transportId) = try await makeForwardingTransport()
        _ = await interfaceB.drainSentPackets()

        // Packet with hopCount = PATHFINDER_M (128): after increment → 129 > 128 → DROP
        let packet = Packet(
            header: PacketHeader(
                headerType: .header2, hasContext: false,
                transportType: .transport, destinationType: .single,
                packetType: .linkRequest, hopCount: UInt8(TransportConstants.PATHFINDER_M)
            ),
            destination: destHash, transportAddress: transportId,
            context: 0x00, data: Data(repeating: 0x55, count: 64)
        )

        await transport.receive(packet: packet, from: "interface-a")
        let sent = await interfaceB.drainSentPackets()
        XCTAssertEqual(sent.count, 0, "Packet at PATHFINDER_M hops should be dropped")
    }

    /// Verify that packet at PATHFINDER_M - 1 hops is forwarded (hops+1 == M).
    func testMaxHopsMinusOneForwarded() async throws {
        let (transport, _, interfaceB, destHash, transportId) = try await makeForwardingTransport()
        _ = await interfaceB.drainSentPackets()

        let packet = Packet(
            header: PacketHeader(
                headerType: .header2, hasContext: false,
                transportType: .transport, destinationType: .single,
                packetType: .linkRequest, hopCount: UInt8(TransportConstants.PATHFINDER_M - 1)
            ),
            destination: destHash, transportAddress: transportId,
            context: 0x00, data: Data(repeating: 0x55, count: 64)
        )

        await transport.receive(packet: packet, from: "interface-a")
        let sent = await interfaceB.drainSentPackets()
        XCTAssertEqual(sent.count, 1, "Packet at PATHFINDER_M-1 hops should be forwarded")

        if let raw = sent.first {
            XCTAssertEqual(raw[1], UInt8(TransportConstants.PATHFINDER_M),
                           "Forwarded hop count should be PATHFINDER_M")
        }
    }

    // MARK: - 8. Timeout Constants

    /// Verify timeout constants match Python.
    /// Python: LINK_TIMEOUT = Link.STALE_TIME * 1.25 = (2 * 360) * 1.25 = 900
    /// Python: REVERSE_TIMEOUT = 8 * 60 = 480
    /// Python: ESTABLISHMENT_TIMEOUT_PER_HOP = 6
    func testTimeoutConstants() {
        XCTAssertEqual(TransportConstants.LINK_TIMEOUT, 900.0,
                       "LINK_TIMEOUT should be 900s (STALE_TIME*1.25, matching Python)")
        XCTAssertEqual(TransportConstants.REVERSE_TIMEOUT, 480.0,
                       "REVERSE_TIMEOUT should be 480s (8*60, matching Python)")
        XCTAssertEqual(LinkConstants.ESTABLISHMENT_TIMEOUT_PER_HOP, 6.0,
                       "ESTABLISHMENT_TIMEOUT_PER_HOP should be 6s (matching Python)")
    }

    // MARK: - 9. Proof Data Format

    /// Verify LINKPROOF data lengths are correctly validated.
    func testProofDataLengths() {
        // 96 bytes: sig(64) + enc_pubkey(32)
        let proof96 = hex(
            "0102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f20" +
            "2122232425262728292a2b2c2d2e2f303132333435363738393a3b3c3d3e3f40" +
            "4142434445464748494a4b4c4d4e4f505152535455565758595a5b5c5d5e5f60"
        )
        XCTAssertEqual(proof96.count, 96, "Proof without signaling should be 96 bytes")

        // Verify structure
        let sig = proof96.prefix(64)
        let encPub = proof96.subdata(in: 64..<96)
        XCTAssertEqual(sig.count, 64, "Signature should be 64 bytes")
        XCTAssertEqual(encPub.count, 32, "Enc pubkey should be 32 bytes")

        // 99 bytes: sig(64) + enc_pubkey(32) + signaling(3)
        let proof99 = proof96 + hex("2001f4")
        XCTAssertEqual(proof99.count, 99, "Proof with signaling should be 99 bytes")

        // Verify signaling extraction
        let signaling = proof99.subdata(in: 96..<99)
        XCTAssertEqual(signaling, hex("2001f4"), "Signaling should be last 3 bytes")
    }

    // MARK: - 10. Flags Byte Conversion (H1 ↔ H2)

    /// Verify that converting between H1 and H2 changes the correct bits.
    func testFlagsByteH1ToH2Conversion() {
        // H1 LINKREQUEST: 0b00000010 = 0x02
        let h1Lr = PacketHeader(
            headerType: .header1, hasContext: false,
            transportType: .broadcast, destinationType: .single,
            packetType: .linkRequest, hopCount: 0
        )
        XCTAssertEqual(h1Lr.encode()[0], 0x02, "H1 LINKREQUEST flags should be 0x02")

        // H2 LINKREQUEST: 0b01010010 = 0x52
        let h2Lr = PacketHeader(
            headerType: .header2, hasContext: false,
            transportType: .transport, destinationType: .single,
            packetType: .linkRequest, hopCount: 0
        )
        XCTAssertEqual(h2Lr.encode()[0], 0x52, "H2 LINKREQUEST flags should be 0x52")

        // Difference is bit 6 (header type) and bit 4 (transport type)
        XCTAssertEqual(h2Lr.encode()[0] ^ h1Lr.encode()[0], 0x50,
                       "H1→H2 should flip bits 6 and 4 (0x50)")
    }

    /// Verify all common flag byte values match Python.
    func testFlagsByteValues() {
        // H1 DATA single
        XCTAssertEqual(
            PacketHeader(headerType: .header1, hasContext: false, transportType: .broadcast,
                         destinationType: .single, packetType: .data, hopCount: 0).encode()[0],
            0x00
        )
        // H2 DATA single
        XCTAssertEqual(
            PacketHeader(headerType: .header2, hasContext: false, transportType: .transport,
                         destinationType: .single, packetType: .data, hopCount: 0).encode()[0],
            0x50
        )
        // H1 PROOF link
        XCTAssertEqual(
            PacketHeader(headerType: .header1, hasContext: false, transportType: .broadcast,
                         destinationType: .link, packetType: .proof, hopCount: 0).encode()[0],
            0x0F
        )
        // H1 PROOF single
        XCTAssertEqual(
            PacketHeader(headerType: .header1, hasContext: false, transportType: .broadcast,
                         destinationType: .single, packetType: .proof, hopCount: 0).encode()[0],
            0x03
        )
        // H1 ANNOUNCE single
        XCTAssertEqual(
            PacketHeader(headerType: .header1, hasContext: false, transportType: .broadcast,
                         destinationType: .single, packetType: .announce, hopCount: 0).encode()[0],
            0x01
        )
        // H1 DATA plain
        XCTAssertEqual(
            PacketHeader(headerType: .header1, hasContext: false, transportType: .broadcast,
                         destinationType: .plain, packetType: .data, hopCount: 0).encode()[0],
            0x08
        )
        // H1 DATA link
        XCTAssertEqual(
            PacketHeader(headerType: .header1, hasContext: false, transportType: .broadcast,
                         destinationType: .link, packetType: .data, hopCount: 0).encode()[0],
            0x0C
        )
    }

    // MARK: - 11. Hashable Part Stripping

    /// Verify that H2 getHashablePart strips the transport address.
    func testH2HashablePartStripsTransportAddr() {
        let dataPayload = "test".data(using: .utf8)!
        let h2Packet = Packet(
            header: PacketHeader(
                headerType: .header2, hasContext: false,
                transportType: .transport, destinationType: .single,
                packetType: .data, hopCount: 3
            ),
            destination: destHash,
            transportAddress: transportAddrIn,
            context: 0x00,
            data: dataPayload
        )

        let hashable = h2Packet.getHashablePart()

        // Should be: (flags & 0x0F) + dest(16) + context(1) + data
        // flags = 0x50, masked = 0x00
        XCTAssertEqual(hashable[0], 0x00, "Masked flags should strip upper nibble")

        // Should NOT contain transport address
        let hashableHex = hexString(hashable)
        let transportHex = hexString(transportAddrIn)
        XCTAssertFalse(hashableHex.contains(transportHex),
                        "Hashable part should not contain transport address")

        // Should contain destination
        let destHex = hexString(destHash)
        XCTAssertTrue(hashableHex.contains(destHex),
                       "Hashable part should contain destination")
    }

    /// Verify that H1 and H2 of the same content produce the same hashable part.
    func testH1H2SameHashablePart() {
        let payload = Data(repeating: 0x42, count: 32)

        let h1 = Packet(
            header: PacketHeader(
                headerType: .header1, hasContext: false,
                transportType: .broadcast, destinationType: .single,
                packetType: .data, hopCount: 0
            ),
            destination: destHash, context: 0x00, data: payload
        )
        let h2 = Packet(
            header: PacketHeader(
                headerType: .header2, hasContext: false,
                transportType: .transport, destinationType: .single,
                packetType: .data, hopCount: 5
            ),
            destination: destHash, transportAddress: transportAddrIn,
            context: 0x00, data: payload
        )

        XCTAssertEqual(h1.getHashablePart(), h2.getHashablePart(),
                       "H1 and H2 with same content should produce the same hashable part")
    }

    // MARK: - 12. computeLinkIdFromPacket (transport actor method)

    /// Verify that the transport's computeLinkIdFromPacket matches manual computation.
    func testComputeLinkIdFromPacket() async throws {
        let transport = ReticulumTransport()

        let h2Packet = Packet(
            header: PacketHeader(
                headerType: .header2, hasContext: false,
                transportType: .transport, destinationType: .single,
                packetType: .linkRequest, hopCount: 2
            ),
            destination: destHash,
            transportAddress: transportAddrIn,
            context: 0x00,
            data: lrData
        )

        let linkId = await transport.computeLinkIdFromPacket(h2Packet)
        XCTAssertEqual(linkId, expectedLinkId,
                       "computeLinkIdFromPacket should match Python link_id")
    }

    // MARK: - 13. Full Forwarding Wire Bytes

    /// End-to-end: forward LINKREQUEST through transport actor and verify wire bytes.
    func testForwardedLinkRequestWireBytes() async throws {
        let (transport, _, interfaceB, _, transportId) = try await makeForwardingTransport()
        _ = await interfaceB.drainSentPackets()

        // Build H2 LINKREQUEST with our test data
        let packet = Packet(
            header: PacketHeader(
                headerType: .header2, hasContext: false,
                transportType: .transport, destinationType: .single,
                packetType: .linkRequest, hopCount: 1
            ),
            destination: Data(repeating: 0xAA, count: 16),  // matches makeForwardingTransport dest
            transportAddress: transportId,
            context: 0x00,
            data: Data(repeating: 0x55, count: 64)  // 64 bytes = ECPUBSIZE (no signaling)
        )

        await transport.receive(packet: packet, from: "interface-a")
        let sent = await interfaceB.drainSentPackets()
        XCTAssertEqual(sent.count, 1, "Should forward one packet")

        if let raw = sent.first {
            // Verify wire format
            XCTAssertEqual(raw[0], 0x52, "Forwarded should be H2 LINKREQUEST (0x52)")
            XCTAssertEqual(raw[1], 2, "Hops should be incremented to 2")

            // Transport address should be the nextHop (0xCC * 16)
            let transportAddr = Data(raw[2..<18])
            XCTAssertEqual(transportAddr, Data(repeating: 0xCC, count: 16),
                           "Transport address should be nextHop from path table")

            // Destination should be preserved
            let dest = Data(raw[18..<34])
            XCTAssertEqual(dest, Data(repeating: 0xAA, count: 16),
                           "Destination should be preserved through forwarding")

            // Context byte
            XCTAssertEqual(raw[34], 0x00, "Context should be preserved")

            // Data should be preserved
            let data = Data(raw[35...])
            XCTAssertEqual(data, Data(repeating: 0x55, count: 64),
                           "Data should be preserved through forwarding")
        }
    }

    // MARK: - 14. Reverse Table Population on DATA Forward

    /// Verify that forwarding a DATA packet creates a reverse table entry
    /// keyed by the packet's truncated hash.
    func testReverseTablePopulatedOnDataForward() async throws {
        let (transport, _, _, destHash, transportId) = try await makeForwardingTransport()

        let dataPayload = Data(repeating: 0x42, count: 50)
        let packet = Packet(
            header: PacketHeader(
                headerType: .header2, hasContext: false,
                transportType: .transport, destinationType: .single,
                packetType: .data, hopCount: 1
            ),
            destination: destHash,
            transportAddress: transportId,
            context: 0x00,
            data: dataPayload
        )

        let expectedKey = packet.getTruncatedHash()

        await transport.receive(packet: packet, from: "interface-a")

        let reverseTable = await transport.reverseTable
        XCTAssertEqual(reverseTable.count, 1, "Should have one reverse table entry")

        guard let entry = reverseTable[expectedKey] else {
            XCTFail("Reverse table key should be packet's truncated hash")
            return
        }
        XCTAssertEqual(entry.receivingInterfaceId, "interface-a",
                       "Receiving interface should be where packet came from")
        XCTAssertEqual(entry.outboundInterfaceId, "interface-b",
                       "Outbound interface should be where packet was forwarded")
    }

    // MARK: - 15. Proof Timeout Computation

    /// Verify proof timeout formula matches Python:
    /// extra + ESTABLISHMENT_TIMEOUT_PER_HOP * max(1, remainingHops)
    func testProofTimeoutFormula() async throws {
        let (transport, _, _, destHash, transportId) = try await makeForwardingTransport()

        let packet = Packet(
            header: PacketHeader(
                headerType: .header2, hasContext: false,
                transportType: .transport, destinationType: .single,
                packetType: .linkRequest, hopCount: 1
            ),
            destination: destHash,
            transportAddress: transportId,
            context: 0x00,
            data: Data(repeating: 0x55, count: 64)
        )

        let before = Date()
        await transport.receive(packet: packet, from: "interface-a")
        let after = Date()

        let linkTable = await transport.linkTable
        guard let (_, entry) = linkTable.first else {
            XCTFail("No link table entry")
            return
        }

        // Expected: ESTABLISHMENT_TIMEOUT_PER_HOP * max(1, remainingHops=2) = 6 * 2 = 12s
        // Plus extra_timeout from bitrate (0 for mock interface)
        let expectedMinTimeout = before.addingTimeInterval(
            LinkConstants.ESTABLISHMENT_TIMEOUT_PER_HOP * Double(max(1, 2))
        )
        let expectedMaxTimeout = after.addingTimeInterval(
            LinkConstants.ESTABLISHMENT_TIMEOUT_PER_HOP * Double(max(1, 2)) + 1.0
        )

        XCTAssertGreaterThanOrEqual(entry.proofTimeout, expectedMinTimeout,
                                     "Proof timeout should be at least ETPH * remainingHops")
        XCTAssertLessThanOrEqual(entry.proofTimeout, expectedMaxTimeout,
                                  "Proof timeout should not exceed expected + margin")
    }

    // MARK: - Test Helpers

    /// Create transport with two interfaces and a path entry for forwarding tests.
    private func makeForwardingTransport() async throws -> (
        transport: ReticulumTransport,
        interfaceA: MockInterface,
        interfaceB: MockInterface,
        destHash: Data,
        transportId: Data
    ) {
        let destHash = Data(repeating: 0xAA, count: 16)
        let transportId = Data(repeating: 0xBB, count: 16)
        let nextHop = Data(repeating: 0xCC, count: 16)

        let pathTable = PathTable()
        let entry = PathEntry(
            destinationHash: destHash,
            publicKeys: Data(),
            interfaceId: "interface-b",
            hopCount: 2,
            randomBlob: Data(repeating: 0x22, count: 10),
            nextHop: nextHop
        )
        await pathTable.record(entry: entry)

        let transport = ReticulumTransport(pathTable: pathTable)
        let interfaceA = MockInterface(id: "interface-a")
        let interfaceB = MockInterface(id: "interface-b")
        try await transport.addInterface(interfaceA)
        try await transport.addInterface(interfaceB)

        let identity = Identity()
        await transport.setTransportEnabled(true, identity: identity)
        await transport.setTransportIdentityHashForTest(transportId)

        return (transport, interfaceA, interfaceB, destHash, transportId)
    }
}
