//
//  TransportInteropTests.swift
//  ReticulumSwift
//
//  E2E interop tests verifying Swift matches Python RNS reference byte-for-byte.
//  Test vectors generated by test-tools/generate_interop_vectors.py
//

import XCTest
import CryptoKit
@testable import ReticulumSwift

final class TransportInteropTests: XCTestCase {

    // MARK: - Hex Helpers

    private func hex(_ s: String) -> Data {
        var data = Data()
        var index = s.startIndex
        while index < s.endIndex {
            let next = s.index(index, offsetBy: 2)
            data.append(UInt8(s[index..<next], radix: 16)!)
            index = next
        }
        return data
    }

    // ============================================================
    // MARK: - 1. Packet Encoding / Hashing
    // ============================================================

    /// HEADER_1 data packet encodes to exact Python wire bytes.
    func testHeader1PacketEncode() throws {
        let destHash = hex("0102030405060708090a0b0c0d0e0f10")
        let payload = hex("48656c6c6f205265746963756c756d")
        let expectedRaw = hex("00030102030405060708090a0b0c0d0e0f100048656c6c6f205265746963756c756d")

        let header = PacketHeader(
            headerType: .header1,
            hasContext: false,
            transportType: .broadcast,
            destinationType: .single,
            packetType: .data,
            hopCount: 3
        )
        let packet = Packet(header: header, destination: destHash, context: 0x00, data: payload)
        XCTAssertEqual(packet.encode(), expectedRaw, "HEADER_1 encode should match Python")
    }

    /// HEADER_2 data packet encodes to exact Python wire bytes.
    func testHeader2PacketEncode() throws {
        let destHash = hex("0102030405060708090a0b0c0d0e0f10")
        let transportAddr = hex("a1a2a3a4a5a6a7a8a9aaabacadaeafb0")
        let payload = hex("48656c6c6f205265746963756c756d")
        let expectedRaw = hex("5005a1a2a3a4a5a6a7a8a9aaabacadaeafb00102030405060708090a0b0c0d0e0f100048656c6c6f205265746963756c756d")

        let header = PacketHeader(
            headerType: .header2,
            hasContext: false,
            transportType: .transport,
            destinationType: .single,
            packetType: .data,
            hopCount: 5
        )
        let packet = Packet(
            header: header,
            destination: destHash,
            transportAddress: transportAddr,
            context: 0x00,
            data: payload
        )
        XCTAssertEqual(packet.encode(), expectedRaw, "HEADER_2 encode should match Python")
    }

    /// HEADER_1 hashable part matches Python (masked header byte, skip hop count).
    func testHeader1HashablePart() throws {
        let raw = hex("00030102030405060708090a0b0c0d0e0f100048656c6c6f205265746963756c756d")
        let expectedHashable = hex("000102030405060708090a0b0c0d0e0f100048656c6c6f205265746963756c756d")

        let packet = try Packet(from: raw)
        XCTAssertEqual(packet.getHashablePart(), expectedHashable, "HEADER_1 hashable part should match Python")
    }

    /// HEADER_2 hashable part matches Python (masked header, skip hop + transport address).
    func testHeader2HashablePart() throws {
        let raw = hex("5005a1a2a3a4a5a6a7a8a9aaabacadaeafb00102030405060708090a0b0c0d0e0f100048656c6c6f205265746963756c756d")
        let expectedHashable = hex("000102030405060708090a0b0c0d0e0f100048656c6c6f205265746963756c756d")

        let packet = try Packet(from: raw)
        XCTAssertEqual(packet.getHashablePart(), expectedHashable, "HEADER_2 hashable part should match Python")
    }

    /// H1 and H2 packets with same dest+context+data produce identical hashes
    /// (transport addr and hop count are excluded from hash computation).
    func testHeader1AndHeader2ProduceSameHash() throws {
        let raw1 = hex("00030102030405060708090a0b0c0d0e0f100048656c6c6f205265746963756c756d")
        let raw2 = hex("5005a1a2a3a4a5a6a7a8a9aaabacadaeafb00102030405060708090a0b0c0d0e0f100048656c6c6f205265746963756c756d")

        let p1 = try Packet(from: raw1)
        let p2 = try Packet(from: raw2)
        XCTAssertEqual(p1.getFullHash(), p2.getFullHash(), "H1 and H2 should produce same packet hash")
    }

    /// Full hash (32 bytes) matches Python SHA-256 output.
    func testFullHash() throws {
        let raw = hex("00030102030405060708090a0b0c0d0e0f100048656c6c6f205265746963756c756d")
        let expectedFullHash = hex("f5c9269b1dbc1dc5678288e8f3be3937f8083e44ea9c5c53df8c12a687d0cd9a")

        let packet = try Packet(from: raw)
        XCTAssertEqual(packet.getFullHash(), expectedFullHash, "Full hash should match Python")
    }

    /// Truncated hash (first 16 bytes) matches Python.
    func testTruncatedHash() throws {
        let raw = hex("00030102030405060708090a0b0c0d0e0f100048656c6c6f205265746963756c756d")
        let expectedTruncHash = hex("f5c9269b1dbc1dc5678288e8f3be3937")

        let packet = try Packet(from: raw)
        XCTAssertEqual(packet.getTruncatedHash(), expectedTruncHash, "Truncated hash should match Python")
    }

    /// Announce packet hash matches Python (different packet type bits).
    func testAnnouncePacketHash() throws {
        let raw = hex("01000102030405060708090a0b0c0d0e0f1000010203")
        let expectedFullHash = hex("cf0803e89c03679693e296b5ef06eaf0288df879d75132650e6c3d2234b14f9c")

        let packet = try Packet(from: raw)
        XCTAssertEqual(packet.getFullHash(), expectedFullHash, "Announce packet hash should match Python")
    }

    /// Packet decode→encode round-trip preserves exact bytes.
    func testPacketRoundTrip() throws {
        let origH1 = hex("00030102030405060708090a0b0c0d0e0f100048656c6c6f205265746963756c756d")
        let origH2 = hex("5005a1a2a3a4a5a6a7a8a9aaabacadaeafb00102030405060708090a0b0c0d0e0f100048656c6c6f205265746963756c756d")

        XCTAssertEqual(try Packet(from: origH1).encode(), origH1, "H1 round-trip should preserve bytes")
        XCTAssertEqual(try Packet(from: origH2).encode(), origH2, "H2 round-trip should preserve bytes")
    }

    /// Header flags byte encodes correctly.
    func testHeaderFlagsByte() {
        // HEADER_1, no context, broadcast, single, data, hop=3 → 0x00
        let h1 = PacketHeader(
            headerType: .header1, hasContext: false, transportType: .broadcast,
            destinationType: .single, packetType: .data, hopCount: 3
        )
        XCTAssertEqual(h1.encode(), Data([0x00, 0x03]))

        // HEADER_2, no context, transport, single, data, hop=5 → 0x50
        let h2 = PacketHeader(
            headerType: .header2, hasContext: false, transportType: .transport,
            destinationType: .single, packetType: .data, hopCount: 5
        )
        XCTAssertEqual(h2.encode(), Data([0x50, 0x05]))

        // HEADER_1, no context, broadcast, single, announce, hop=0 → 0x01
        let ann = PacketHeader(
            headerType: .header1, hasContext: false, transportType: .broadcast,
            destinationType: .single, packetType: .announce, hopCount: 0
        )
        XCTAssertEqual(ann.encode(), Data([0x01, 0x00]))

        // HEADER_1, hasContext, broadcast, single, announce, hop=0 → 0x21
        let annCtx = PacketHeader(
            headerType: .header1, hasContext: true, transportType: .broadcast,
            destinationType: .single, packetType: .announce, hopCount: 0
        )
        XCTAssertEqual(annCtx.encode(), Data([0x21, 0x00]))

        // HEADER_1, no context, broadcast, plain, announce, hop=0 → 0x09
        let annPlain = PacketHeader(
            headerType: .header1, hasContext: false, transportType: .broadcast,
            destinationType: .plain, packetType: .announce, hopCount: 0
        )
        XCTAssertEqual(annPlain.encode(), Data([0x09, 0x00]))

        // HEADER_1, broadcast, single, linkRequest, hop=0 → 0x02
        let lr = PacketHeader(
            headerType: .header1, hasContext: false, transportType: .broadcast,
            destinationType: .single, packetType: .linkRequest, hopCount: 0
        )
        XCTAssertEqual(lr.encode(), Data([0x02, 0x00]))
    }

    // ============================================================
    // MARK: - 2. Identity & Destination Hashing
    // ============================================================

    /// Identity hash from known public keys matches Python.
    func testIdentityHash() throws {
        let encPub = hex("8f40c5adb68f25624ae5b214ea767a6ec94d829d3d7b5e1ad1ba6f3e2138285f")
        let sigPub = hex("29acbae141bccaf0b22e1a94d34d0bc7361e526d0bfe12c89794bc9322966dd7")
        let expectedHash = hex("aca31af0441d81dbec71e82da0b4b5f5")

        let hash = Hashing.identityHash(encryptionPublicKey: encPub, signingPublicKey: sigPub)
        XCTAssertEqual(hash, expectedHash, "Identity hash should match Python")
    }

    /// Identity created from private keys derives same public keys as Python.
    func testIdentityPublicKeyDerivation() throws {
        let encPriv = hex("000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f")
        let sigPriv = hex("202122232425262728292a2b2c2d2e2f303132333435363738393a3b3c3d3e3f")
        let expectedEncPub = hex("8f40c5adb68f25624ae5b214ea767a6ec94d829d3d7b5e1ad1ba6f3e2138285f")
        let expectedSigPub = hex("29acbae141bccaf0b22e1a94d34d0bc7361e526d0bfe12c89794bc9322966dd7")

        let identity = try Identity(encryptionPrivateKeyBytes: encPriv, signingPrivateKeyBytes: sigPriv)
        XCTAssertEqual(Data(identity.encryptionPublicKey.rawRepresentation), expectedEncPub, "Enc pub should match Python")
        XCTAssertEqual(Data(identity.signingPublicKey.rawRepresentation), expectedSigPub, "Sig pub should match Python")
        XCTAssertEqual(identity.hash, hex("aca31af0441d81dbec71e82da0b4b5f5"), "Identity hash should match Python")
    }

    /// Name hash matches Python: SHA256("lxmf.delivery")[:10].
    func testNameHash() {
        let expected = hex("6ec60bc318e2c0f0d908")
        let result = Hashing.destinationNameHash(appName: "lxmf", aspects: ["delivery"])
        XCTAssertEqual(result, expected, "Name hash for lxmf.delivery should match Python")
    }

    /// Name hash for different app name matches Python.
    func testNameHashNomadnet() {
        let expected = hex("213e6311bcec54ab4fde")
        let result = Hashing.destinationNameHash(appName: "nomadnetwork", aspects: ["node"])
        XCTAssertEqual(result, expected, "Name hash for nomadnetwork.node should match Python")
    }

    /// SINGLE destination hash matches Python: truncHash(nameHash || identityHash).
    func testDestinationHashSingle() throws {
        let encPriv = hex("000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f")
        let sigPriv = hex("202122232425262728292a2b2c2d2e2f303132333435363738393a3b3c3d3e3f")
        let expected = hex("fae321c442e3c9bdcd7a3e79d850e03c")

        let identity = try Identity(encryptionPrivateKeyBytes: encPriv, signingPrivateKeyBytes: sigPriv)
        let dest = Destination(identity: identity, appName: "lxmf", aspects: ["delivery"])
        XCTAssertEqual(dest.hash, expected, "SINGLE dest hash should match Python")
    }

    /// SINGLE destination hash for nomadnetwork.node matches Python.
    func testDestinationHashSingleNomadnet() throws {
        let encPriv = hex("000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f")
        let sigPriv = hex("202122232425262728292a2b2c2d2e2f303132333435363738393a3b3c3d3e3f")
        let expected = hex("8e484af42dd1c865a87fb2d16a5d8e63")

        let identity = try Identity(encryptionPrivateKeyBytes: encPriv, signingPrivateKeyBytes: sigPriv)
        let dest = Destination(identity: identity, appName: "nomadnetwork", aspects: ["node"])
        XCTAssertEqual(dest.hash, expected, "nomadnetwork.node dest hash should match Python")
    }

    /// PLAIN destination hash matches Python: truncHash(nameHash).
    func testDestinationHashPlain() {
        let expected = hex("9497d16c52ac5faec04c36db5c301e8e")
        let dest = Destination(plainAppName: "lxmf", aspects: ["delivery"])
        XCTAssertEqual(dest.hash, expected, "PLAIN dest hash should match Python")
    }

    /// Static hash computation from public key bytes matches Python.
    func testStaticDestinationHashFromPubKeys() {
        let encPub = hex("8f40c5adb68f25624ae5b214ea767a6ec94d829d3d7b5e1ad1ba6f3e2138285f")
        let sigPub = hex("29acbae141bccaf0b22e1a94d34d0bc7361e526d0bfe12c89794bc9322966dd7")
        let expected = hex("fae321c442e3c9bdcd7a3e79d850e03c")

        let hash = Destination.hash(
            encryptionPublicKey: encPub,
            signingPublicKey: sigPub,
            appName: "lxmf",
            aspects: ["delivery"]
        )
        XCTAssertEqual(hash, expected, "Static dest hash from pub keys should match Python")
    }

    // ============================================================
    // MARK: - 3. Announce Wire Format
    // ============================================================

    /// Announce payload structure matches Python layout.
    func testAnnouncePayloadStructure() throws {
        let encPriv = hex("000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f")
        let sigPriv = hex("202122232425262728292a2b2c2d2e2f303132333435363738393a3b3c3d3e3f")
        let randomHash = hex("aabbccddee0065e11a80")
        let appData = "TestApp v1.0".data(using: .utf8)!

        let identity = try Identity(encryptionPrivateKeyBytes: encPriv, signingPrivateKeyBytes: sigPriv)
        let dest = Destination(identity: identity, appName: "lxmf", aspects: ["delivery"])
        let announce = Announce(destination: dest, appData: appData, randomHash: randomHash)
        let payload = try announce.build()

        // Verify structure: pubkeys(64) + nameHash(10) + randomHash(10) + signature(64) + appData(12) = 160
        XCTAssertEqual(payload.count, 160, "Announce payload should be 160 bytes")

        // Extract components
        let pubKeys = Data(payload[0..<64])
        let nameHash = Data(payload[64..<74])
        let extractedRandom = Data(payload[74..<84])
        let signature = Data(payload[84..<148])
        let extractedAppData = Data(payload[148...])

        XCTAssertEqual(pubKeys, identity.publicKeys, "Public keys should match")
        XCTAssertEqual(nameHash, dest.nameHash, "Name hash should match")
        XCTAssertEqual(extractedRandom, randomHash, "Random hash should match")
        XCTAssertEqual(signature.count, 64, "Signature should be 64 bytes")
        XCTAssertEqual(extractedAppData, appData, "App data should match")
    }

    /// Python can verify our announce signature (structure matches).
    func testAnnounceSignatureVerifiable() throws {
        let encPriv = hex("000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f")
        let sigPriv = hex("202122232425262728292a2b2c2d2e2f303132333435363738393a3b3c3d3e3f")
        let randomHash = hex("aabbccddee0065e11a80")
        let appData = "TestApp v1.0".data(using: .utf8)!

        let identity = try Identity(encryptionPrivateKeyBytes: encPriv, signingPrivateKeyBytes: sigPriv)
        let dest = Destination(identity: identity, appName: "lxmf", aspects: ["delivery"])

        // Build signed data the same way Python does
        var signedData = Data()
        signedData.append(dest.hash)
        signedData.append(identity.publicKeys)
        signedData.append(dest.nameHash)
        signedData.append(randomHash)
        signedData.append(appData)

        XCTAssertEqual(signedData, hex("fae321c442e3c9bdcd7a3e79d850e03c8f40c5adb68f25624ae5b214ea767a6ec94d829d3d7b5e1ad1ba6f3e2138285f29acbae141bccaf0b22e1a94d34d0bc7361e526d0bfe12c89794bc9322966dd76ec60bc318e2c0f0d908aabbccddee0065e11a80546573744170702076312e30"),
                       "Signed data should match Python byte-for-byte")

        // Sign and verify
        let announce = Announce(destination: dest, appData: appData, randomHash: randomHash)
        let payload = try announce.build()
        let signature = Data(payload[84..<148])

        // Verify our own signature
        XCTAssertTrue(identity.verify(signature: signature, for: signedData),
                      "Swift signature should be verifiable with identity public key")
    }

    /// Python-generated announce signature is verifiable by Swift.
    func testVerifyPythonAnnounceSignature() throws {
        let sigPub = hex("29acbae141bccaf0b22e1a94d34d0bc7361e526d0bfe12c89794bc9322966dd7")
        let signedData = hex("fae321c442e3c9bdcd7a3e79d850e03c8f40c5adb68f25624ae5b214ea767a6ec94d829d3d7b5e1ad1ba6f3e2138285f29acbae141bccaf0b22e1a94d34d0bc7361e526d0bfe12c89794bc9322966dd76ec60bc318e2c0f0d908aabbccddee0065e11a80546573744170702076312e30")
        let pythonSig = hex("a3d4545e587f95175a4b7096b12913406848fb575a6a0ae034b0db14b4bcf6f8f0c981e7f77c4458d75b1ca59b944bb3655822672c92db0bcfdf2dbd0a70f605")

        let valid = try Identity.verify(signature: pythonSig, for: signedData, publicKey: sigPub)
        XCTAssertTrue(valid, "Python announce signature should verify in Swift")
    }

    /// Announce with ratchet: signature from Python is verifiable.
    func testVerifyPythonRatchetAnnounceSignature() throws {
        let sigPub = hex("29acbae141bccaf0b22e1a94d34d0bc7361e526d0bfe12c89794bc9322966dd7")
        let signedData = hex("fae321c442e3c9bdcd7a3e79d850e03c8f40c5adb68f25624ae5b214ea767a6ec94d829d3d7b5e1ad1ba6f3e2138285f29acbae141bccaf0b22e1a94d34d0bc7361e526d0bfe12c89794bc9322966dd76ec60bc318e2c0f0d908aabbccddee0065e11a80404142434445464748494a4b4c4d4e4f505152535455565758595a5b5c5d5e5f546573744170702076312e30")
        let pythonSig = hex("8d09de7d8b231e7970fa85f086060f9fc4e4437ecc6cef90e7ba76feb3f32d2acca8dd83aa2ad50841917ded9f6afa7db58b99c5176bc324a084479a38dee409")

        let valid = try Identity.verify(signature: pythonSig, for: signedData, publicKey: sigPub)
        XCTAssertTrue(valid, "Python ratchet announce signature should verify in Swift")
    }

    /// Announce with ratchet includes ratchet key in payload and sets hasContext.
    func testAnnounceWithRatchetFormat() throws {
        let encPriv = hex("000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f")
        let sigPriv = hex("202122232425262728292a2b2c2d2e2f303132333435363738393a3b3c3d3e3f")
        let randomHash = hex("aabbccddee0065e11a80")
        let ratchetKey = hex("404142434445464748494a4b4c4d4e4f505152535455565758595a5b5c5d5e5f")
        let appData = "TestApp v1.0".data(using: .utf8)!

        let identity = try Identity(encryptionPrivateKeyBytes: encPriv, signingPrivateKeyBytes: sigPriv)
        let dest = Destination(identity: identity, appName: "lxmf", aspects: ["delivery"])
        let announce = Announce(
            destination: dest, appData: appData, randomHash: randomHash, ratchet: ratchetKey
        )

        // Payload should be: pubkeys(64) + nameHash(10) + randomHash(10) + ratchet(32) + sig(64) + appData(12) = 192
        let payload = try announce.build()
        XCTAssertEqual(payload.count, 192, "Ratchet announce payload should be 192 bytes")

        // Ratchet key at offset 84
        let extractedRatchet = Data(payload[84..<116])
        XCTAssertEqual(extractedRatchet, ratchetKey, "Ratchet key should be at correct offset")

        // Packet should have hasContext=true
        let packet = try announce.buildPacket()
        XCTAssertTrue(packet.header.hasContext, "Ratchet announce should set hasContext")
        XCTAssertEqual(packet.header.encode()[0], 0x21, "Flags byte should be 0x21 with context")
    }

    /// PLAIN announce has no signature, just nameHash + randomHash + appData.
    func testPlainAnnounceFormat() throws {
        let randomHash = hex("aabbccddee0065e11a80")
        let appData = "TestApp v1.0".data(using: .utf8)!
        let expectedPayload = hex("4a6624c05d22cb16eca5aabbccddee0065e11a80546573744170702076312e30")

        let dest = Destination(plainAppName: "test", aspects: ["plain"])
        let announce = Announce(destination: dest, appData: appData, randomHash: randomHash)
        let payload = try announce.build()

        XCTAssertEqual(payload, expectedPayload, "PLAIN announce payload should match Python")
    }

    /// Random hash timestamp encoding matches Python: bytes[5:10] = big-endian Unix timestamp.
    func testRandomHashTimestamp() {
        let randomHash = hex("aabbccddee0065e11a80")

        // Extract timestamp from bytes [5:10]
        let tsBytes = Data(randomHash[5..<10])
        var ts: UInt64 = 0
        for b in tsBytes {
            ts = (ts << 8) | UInt64(b)
        }
        XCTAssertEqual(ts, 1709251200, "Extracted timestamp should match")
    }

    // ============================================================
    // MARK: - 4. Link ID Computation
    // ============================================================

    /// Link ID from LINKREQUEST matches Python computation.
    func testLinkIdComputation() throws {
        let ephEncPriv = hex("6465666768696a6b6c6d6e6f707172737475767778797a7b7c7d7e7f80818283")
        let ephSigPriv = hex("8485868788898a8b8c8d8e8f909192939495969798999a9b9c9d9e9fa0a1a2a3")
        let expectedLinkId = hex("e8808769e59cf2f4c1805801cdf64985")

        // Create identity and destination for the link request
        let encPriv = hex("000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f")
        let sigPriv = hex("202122232425262728292a2b2c2d2e2f303132333435363738393a3b3c3d3e3f")
        let identity = try Identity(encryptionPrivateKeyBytes: encPriv, signingPrivateKeyBytes: sigPriv)
        let dest = Destination(identity: identity, appName: "lxmf", aspects: ["delivery"])

        // Create link request with known ephemeral keys
        let ephEncKey = try Curve25519.KeyAgreement.PrivateKey(rawRepresentation: ephEncPriv)
        let ephSigKey = try Curve25519.Signing.PrivateKey(rawRepresentation: ephSigPriv)

        let lr = LinkRequest(
            destination: dest,
            ephemeralEncryptionPrivateKey: ephEncKey,
            ephemeralSigningPrivateKey: ephSigKey,
            signaling: Data([0x20, 0x01, 0xF4])  // default MTU 500
        )

        // Verify public keys match Python derivation
        XCTAssertEqual(
            Data(lr.ephemeralEncryptionPublicKey.rawRepresentation),
            hex("7d9c24316539825c1896e57f28197746793ce60cbee3ad47da9d07b85fa55e2a"),
            "Ephemeral enc pub should match Python"
        )
        XCTAssertEqual(
            Data(lr.ephemeralSigningPublicKey.rawRepresentation),
            hex("8befe61c3095da4d71f14befe220ff9a76e0c5b5d046204ee3d70761aae839fc"),
            "Ephemeral sig pub should match Python"
        )

        // Request data should be 67 bytes
        XCTAssertEqual(lr.requestData.count, 67, "LR data should be 67 bytes")

        // Link ID should match Python
        XCTAssertEqual(lr.linkId, expectedLinkId, "Link ID should match Python")
    }

    /// LINKREQUEST packet raw bytes match Python.
    func testLinkRequestRawBytes() throws {
        let ephEncPriv = hex("6465666768696a6b6c6d6e6f707172737475767778797a7b7c7d7e7f80818283")
        let ephSigPriv = hex("8485868788898a8b8c8d8e8f909192939495969798999a9b9c9d9e9fa0a1a2a3")
        let expectedRaw = hex("0200fae321c442e3c9bdcd7a3e79d850e03c007d9c24316539825c1896e57f28197746793ce60cbee3ad47da9d07b85fa55e2a8befe61c3095da4d71f14befe220ff9a76e0c5b5d046204ee3d70761aae839fc2001f4")

        let encPriv = hex("000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f")
        let sigPriv = hex("202122232425262728292a2b2c2d2e2f303132333435363738393a3b3c3d3e3f")
        let identity = try Identity(encryptionPrivateKeyBytes: encPriv, signingPrivateKeyBytes: sigPriv)
        let dest = Destination(identity: identity, appName: "lxmf", aspects: ["delivery"])

        let ephEncKey = try Curve25519.KeyAgreement.PrivateKey(rawRepresentation: ephEncPriv)
        let ephSigKey = try Curve25519.Signing.PrivateKey(rawRepresentation: ephSigPriv)

        let lr = LinkRequest(
            destination: dest,
            ephemeralEncryptionPrivateKey: ephEncKey,
            ephemeralSigningPrivateKey: ephSigKey
        )

        XCTAssertEqual(lr.packet().encode(), expectedRaw, "LR packet raw should match Python")
    }

    /// MTU signaling encoding/decoding: mode=1, MTU=500.
    func testDefaultMtuSignaling() {
        XCTAssertEqual(LinkConstants.DEFAULT_MTU_SIGNALING, Data([0x20, 0x01, 0xF4]),
                       "Default signaling should encode mode=1, MTU=500")
    }

    /// MTU signaling for TCP (262144) matches Python.
    func testTcpMtuSignaling() {
        let expected = hex("240000")
        let mtu = 262144
        let mode: Int = 1
        let value = (mode << 21) | mtu
        var signaling = Data(count: 3)
        signaling[0] = UInt8((value >> 16) & 0xFF)
        signaling[1] = UInt8((value >> 8) & 0xFF)
        signaling[2] = UInt8(value & 0xFF)
        XCTAssertEqual(signaling, expected, "TCP MTU signaling should match Python")
    }

    /// MTU signaling for AutoInterface (1196) matches Python.
    func testAutoMtuSignaling() {
        let expected = hex("2004ac")
        let mtu = 1196
        let mode: Int = 1
        let value = (mode << 21) | mtu
        var signaling = Data(count: 3)
        signaling[0] = UInt8((value >> 16) & 0xFF)
        signaling[1] = UInt8((value >> 8) & 0xFF)
        signaling[2] = UInt8(value & 0xFF)
        XCTAssertEqual(signaling, expected, "Auto MTU signaling should match Python")
    }

    // ============================================================
    // MARK: - 5. Key Derivation (HKDF)
    // ============================================================

    /// HKDF with salt, no context, length=64 matches Python.
    func testHKDF64BytesWithSalt() {
        let ikm = hex("000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f")
        let salt = hex("e8808769e59cf2f4c1805801cdf64985")
        let expected = hex("7a685fafdd211c9a6e78d39cb0b4403b547bd47fcef8258b1cd12a46b06f0c790943ee578263da63e31f70c9cdebf9add3508104dac945924a5a5ff04db6f108")

        let result = KeyDerivation.deriveKey(length: 64, inputKeyMaterial: ikm, salt: salt)
        XCTAssertEqual(result, expected, "HKDF 64-byte with salt should match Python")
    }

    /// HKDF with context matches Python.
    func testHKDFWithContext() {
        let ikm = hex("000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f")
        let salt = hex("e8808769e59cf2f4c1805801cdf64985")
        let ctx = "test_context".data(using: .utf8)!
        let expected = hex("409e4f3d0bcf8208240d07844c1bec0f9cfe2dd8e9ef80ee9c23586029db7517d798e63aa40957e830cd667d108a839688d8e3d34c4f1b64b14d51c4390fe9dd")

        let result = KeyDerivation.deriveKey(length: 64, inputKeyMaterial: ikm, salt: salt, context: ctx)
        XCTAssertEqual(result, expected, "HKDF with context should match Python")
    }

    /// HKDF with length=32 matches Python (single block).
    func testHKDF32Bytes() {
        let ikm = hex("000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f")
        let salt = hex("e8808769e59cf2f4c1805801cdf64985")
        let expected = hex("7a685fafdd211c9a6e78d39cb0b4403b547bd47fcef8258b1cd12a46b06f0c79")

        let result = KeyDerivation.deriveKey(length: 32, inputKeyMaterial: ikm, salt: salt)
        XCTAssertEqual(result, expected, "HKDF 32-byte should match Python")
    }

    /// HKDF with no salt (defaults to 32 zero bytes) matches Python.
    func testHKDFNoSalt() {
        let ikm = hex("000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f")
        let expected = hex("37ad29109f43265287804b674e2653d0a513718907f97fca97c95bded8104bbf9601b7e7a7d5a882b151679d3bba7d1ecf9681ad0509bfa68434e1bfa767a51d")

        let result = KeyDerivation.deriveKey(length: 64, inputKeyMaterial: ikm, salt: nil)
        XCTAssertEqual(result, expected, "HKDF with nil salt should match Python")
    }

    // ============================================================
    // MARK: - 6. Token Encryption
    // ============================================================

    /// Token encrypt with known IV matches Python byte-for-byte.
    func testTokenEncryptMatchesPython() throws {
        let derivedKey = hex("7a685fafdd211c9a6e78d39cb0b4403b547bd47fcef8258b1cd12a46b06f0c790943ee578263da63e31f70c9cdebf9add3508104dac945924a5a5ff04db6f108")
        let iv = hex("000102030405060708090a0b0c0d0e0f")
        let plaintext = "Hello, Reticulum!".data(using: .utf8)!
        let expected = hex("000102030405060708090a0b0c0d0e0f583f2eae96cbf7360d05f71a4b405e95de9aa84a9f7eb0f5fd3676032ec972b7c56ddb6a93bea779c44ac925f6e77aac5eaf04d307dabe946d697263d0b26a8b")

        let token = try Token(derivedKey: derivedKey)
        let encrypted = try token.encrypt(plaintext, iv: iv)
        XCTAssertEqual(encrypted, expected, "Token encrypt should match Python byte-for-byte")
    }

    /// Token decrypt of Python-encrypted data produces correct plaintext.
    func testTokenDecryptPythonData() throws {
        let derivedKey = hex("7a685fafdd211c9a6e78d39cb0b4403b547bd47fcef8258b1cd12a46b06f0c790943ee578263da63e31f70c9cdebf9add3508104dac945924a5a5ff04db6f108")
        let encrypted = hex("000102030405060708090a0b0c0d0e0f583f2eae96cbf7360d05f71a4b405e95de9aa84a9f7eb0f5fd3676032ec972b7c56ddb6a93bea779c44ac925f6e77aac5eaf04d307dabe946d697263d0b26a8b")
        let expectedPlaintext = "Hello, Reticulum!".data(using: .utf8)!

        let token = try Token(derivedKey: derivedKey)
        let decrypted = try token.decrypt(encrypted)
        XCTAssertEqual(decrypted, expectedPlaintext, "Token decrypt should produce correct plaintext")
    }

    /// Token encrypt→decrypt round-trip.
    func testTokenRoundTrip() throws {
        let derivedKey = hex("7a685fafdd211c9a6e78d39cb0b4403b547bd47fcef8258b1cd12a46b06f0c790943ee578263da63e31f70c9cdebf9add3508104dac945924a5a5ff04db6f108")
        let plaintext = "Hello, Reticulum!".data(using: .utf8)!

        let token = try Token(derivedKey: derivedKey)
        let encrypted = try token.encrypt(plaintext)
        let decrypted = try token.decrypt(encrypted)
        XCTAssertEqual(decrypted, plaintext, "Token round-trip should preserve plaintext")
    }

    /// Empty plaintext encryption matches Python.
    func testTokenEncryptEmpty() throws {
        let derivedKey = hex("7a685fafdd211c9a6e78d39cb0b4403b547bd47fcef8258b1cd12a46b06f0c790943ee578263da63e31f70c9cdebf9add3508104dac945924a5a5ff04db6f108")
        let iv = hex("000102030405060708090a0b0c0d0e0f")
        let expected = hex("000102030405060708090a0b0c0d0e0f68aeed95fe86b61f14688e348185059f491daca6235ded1b0bce526f7b35e0bbef6f056079085fd6f11bd97df6cf95a5")

        let token = try Token(derivedKey: derivedKey)
        let encrypted = try token.encrypt(Data(), iv: iv)
        XCTAssertEqual(encrypted, expected, "Empty plaintext encryption should match Python")
    }

    /// One full AES block (16 bytes) encryption matches Python.
    func testTokenEncryptOneBlock() throws {
        let derivedKey = hex("7a685fafdd211c9a6e78d39cb0b4403b547bd47fcef8258b1cd12a46b06f0c790943ee578263da63e31f70c9cdebf9add3508104dac945924a5a5ff04db6f108")
        let iv = hex("000102030405060708090a0b0c0d0e0f")
        let data = hex("000102030405060708090a0b0c0d0e0f")
        let expected = hex("000102030405060708090a0b0c0d0e0fce3201f416dd877dff0af313031cdbaf12788df8e8abfd34788408ef73f3fea2d1793eccbbe89503dbe770f649e85892df89b369775457f6713f6bf760f3f2be")

        let token = try Token(derivedKey: derivedKey)
        let encrypted = try token.encrypt(data, iv: iv)
        XCTAssertEqual(encrypted, expected, "One-block encryption should match Python")
    }

    /// Two AES blocks (32 bytes) encryption matches Python.
    func testTokenEncryptTwoBlocks() throws {
        let derivedKey = hex("7a685fafdd211c9a6e78d39cb0b4403b547bd47fcef8258b1cd12a46b06f0c790943ee578263da63e31f70c9cdebf9add3508104dac945924a5a5ff04db6f108")
        let iv = hex("000102030405060708090a0b0c0d0e0f")
        let data = hex("000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f")
        let expected = hex("000102030405060708090a0b0c0d0e0fce3201f416dd877dff0af313031cdbaf7c872d75eb3fa2bdcfa1fc82ca90b51acc96f6a6f9dfdb05c3982e25d4daa5581e87d4cfe514e708a683b5d3b02c0ca2c3291c83fba1aa2cef556f29931c5ae5")

        let token = try Token(derivedKey: derivedKey)
        let encrypted = try token.encrypt(data, iv: iv)
        XCTAssertEqual(encrypted, expected, "Two-block encryption should match Python")
    }

    /// Token with tampered HMAC is rejected.
    func testTokenTamperedHmacRejected() throws {
        let derivedKey = hex("7a685fafdd211c9a6e78d39cb0b4403b547bd47fcef8258b1cd12a46b06f0c790943ee578263da63e31f70c9cdebf9add3508104dac945924a5a5ff04db6f108")
        var encrypted = hex("000102030405060708090a0b0c0d0e0f583f2eae96cbf7360d05f71a4b405e95de9aa84a9f7eb0f5fd3676032ec972b7c56ddb6a93bea779c44ac925f6e77aac5eaf04d307dabe946d697263d0b26a8b")

        // Tamper with last byte of HMAC
        encrypted[encrypted.count - 1] ^= 0xFF

        let token = try Token(derivedKey: derivedKey)
        XCTAssertThrowsError(try token.decrypt(encrypted), "Tampered HMAC should be rejected")
    }

    // ============================================================
    // MARK: - 7. Path Table Constants
    // ============================================================

    /// All path table constants match Python Transport.py values.
    func testPathfinderConstants() {
        XCTAssertEqual(TransportConstants.PATHFINDER_M, 128, "PATHFINDER_M should be 128")
        XCTAssertEqual(TransportConstants.PATHFINDER_R, 1, "PATHFINDER_R should be 1")
        XCTAssertEqual(TransportConstants.PATHFINDER_G, 5.0, "PATHFINDER_G should be 5.0")
        XCTAssertEqual(TransportConstants.PATHFINDER_RW, 0.5, "PATHFINDER_RW should be 0.5")
        XCTAssertEqual(TransportConstants.PATHFINDER_E, 604_800, "PATHFINDER_E should be 604800")
        XCTAssertEqual(TransportConstants.AP_PATH_TIME, 86_400, "AP_PATH_TIME should be 86400")
        XCTAssertEqual(TransportConstants.ROAMING_PATH_TIME, 21_600, "ROAMING_PATH_TIME should be 21600")
    }

    /// Announce and transport table constants match Python.
    func testAnnounceAndTransportConstants() {
        XCTAssertEqual(TransportConstants.LOCAL_REBROADCASTS_MAX, 2)
        XCTAssertEqual(TransportConstants.MAX_RANDOM_BLOBS, 64)
        XCTAssertEqual(TransportConstants.ANNOUNCE_CAP, 0.02, accuracy: 0.001)
        XCTAssertEqual(TransportConstants.REVERSE_TIMEOUT, 480)
        XCTAssertEqual(TransportConstants.LINK_TIMEOUT, 900)
        XCTAssertEqual(TransportConstants.HASHLIST_MAXSIZE, 1_000_000)
        XCTAssertEqual(TransportConstants.PATH_REQUEST_MI, 20.0)
    }

    /// IFAC constants match Python.
    func testIFACConstants() {
        XCTAssertEqual(TransportConstants.IFAC_MIN_SIZE, 1)
        XCTAssertEqual(TransportConstants.DEFAULT_IFAC_SIZE, 16)
        XCTAssertEqual(TransportConstants.IFAC_SALT.count, 32)
        XCTAssertEqual(TransportConstants.IFAC_SALT, hex("adf54d882c9a9b80771eb4995d702d4a3e733391b2a0f53f416d9f907e55cff8"))
    }

    // ============================================================
    // MARK: - 8. Announce Timing
    // ============================================================

    /// Random hash timestamp embedding: bytes[5:10] big-endian Unix time.
    func testRandomHashTimestampEncoding() {
        let timestamp: UInt64 = 1709251200
        var bytes = [UInt8](repeating: 0, count: 10)

        // Random part (first 5 bytes)
        bytes[0] = 0xaa; bytes[1] = 0xbb; bytes[2] = 0xcc; bytes[3] = 0xdd; bytes[4] = 0xee

        // Timestamp (last 5 bytes, big-endian)
        bytes[5] = UInt8((timestamp >> 32) & 0xFF)
        bytes[6] = UInt8((timestamp >> 24) & 0xFF)
        bytes[7] = UInt8((timestamp >> 16) & 0xFF)
        bytes[8] = UInt8((timestamp >> 8) & 0xFF)
        bytes[9] = UInt8(timestamp & 0xFF)

        let expected = hex("aabbccddee0065e11a80")
        XCTAssertEqual(Data(bytes), expected, "Random hash with embedded timestamp should match Python")
    }

    /// Timestamp extraction from random hash matches Python.
    func testRandomHashTimestampExtraction() {
        let randomHash = hex("aabbccddee0065e11a80")

        // Extract 5-byte big-endian timestamp from bytes [5:10]
        var ts: UInt64 = 0
        for i in 5..<10 {
            ts = (ts << 8) | UInt64(randomHash[i])
        }
        XCTAssertEqual(ts, 1709251200, "Extracted timestamp should be 1709251200")
    }

    /// PATHFINDER_G delay is the base delay before first retransmission.
    func testPathfinderGraceDelay() {
        // Python: retransmit_timeout = now + PATHFINDER_G + random(0, PATHFINDER_RW)
        // So minimum delay = PATHFINDER_G = 5.0s, maximum = PATHFINDER_G + PATHFINDER_RW = 5.5s
        let minDelay = TransportConstants.PATHFINDER_G
        let maxDelay = TransportConstants.PATHFINDER_G + TransportConstants.PATHFINDER_RW
        XCTAssertEqual(minDelay, 5.0, "Minimum retransmit delay should be 5.0s")
        XCTAssertEqual(maxDelay, 5.5, "Maximum retransmit delay should be 5.5s")
    }

    // ============================================================
    // MARK: - 9. Packet Context Routing
    // ============================================================

    /// All context byte values match Python Packet.py.
    func testContextByteValues() {
        XCTAssertEqual(PacketContext.NONE, 0x00)
        XCTAssertEqual(PacketContext.RESOURCE, 0x01)
        XCTAssertEqual(PacketContext.RESOURCE_ADV, 0x02)
        XCTAssertEqual(PacketContext.RESOURCE_REQ, 0x03)
        XCTAssertEqual(PacketContext.RESOURCE_HMU, 0x04)
        XCTAssertEqual(PacketContext.RESOURCE_PRF, 0x05)
        XCTAssertEqual(PacketContext.RESOURCE_ICL, 0x06)
        XCTAssertEqual(PacketContext.RESOURCE_RCL, 0x07)
        XCTAssertEqual(PacketContext.CACHE_REQUEST, 0x08)
        XCTAssertEqual(PacketContext.REQUEST, 0x09)
        XCTAssertEqual(PacketContext.RESPONSE, 0x0A)
        XCTAssertEqual(PacketContext.PATH_RESPONSE, 0x0B)
        XCTAssertEqual(PacketContext.COMMAND, 0x0C)
        XCTAssertEqual(PacketContext.COMMAND_STATUS, 0x0D)
        XCTAssertEqual(PacketContext.CHANNEL, 0x0E)
        XCTAssertEqual(PacketContext.KEEPALIVE, 0xFA)
        XCTAssertEqual(PacketContext.LINKIDENTIFY, 0xFB)
        XCTAssertEqual(PacketContext.LINKCLOSE, 0xFC)
        XCTAssertEqual(PacketContext.LRRTT, 0xFE)
        XCTAssertEqual(PacketContext.LRPROOF, 0xFF)
    }

    /// Link context byte values match Python Link.py.
    func testLinkContextValues() {
        XCTAssertEqual(LinkConstants.CONTEXT_KEEPALIVE, 0xFA)
        XCTAssertEqual(LinkConstants.CONTEXT_LINKIDENTIFY, 0xFB)
        XCTAssertEqual(LinkConstants.CONTEXT_LINKCLOSE, 0xFC)
        XCTAssertEqual(LinkConstants.CONTEXT_LRRTT, 0xFE)
        XCTAssertEqual(LinkConstants.CONTEXT_LRPROOF, 0xFF)
    }

    /// Passthrough contexts (NOT link-encrypted) match Python Packet.pack().
    func testPassthroughContexts() {
        // Python Packet.pack() treats these as passthrough (no link encryption):
        // - KEEPALIVE (0xFA): sent as raw 0xFF/0xFE marker
        // - LRPROOF (0xFF): link establishment proof
        // - RESOURCE (0x01): Resource class handles its own encryption
        let passthroughContexts: [UInt8] = [
            PacketContext.KEEPALIVE,
            PacketContext.LRPROOF,
            PacketContext.RESOURCE,
        ]

        XCTAssertTrue(passthroughContexts.contains(0xFA))
        XCTAssertTrue(passthroughContexts.contains(0xFF))
        XCTAssertTrue(passthroughContexts.contains(0x01))
    }

    /// Encrypted contexts (link-encrypted) match Python Packet.pack().
    func testEncryptedContexts() {
        // These contexts are link-encrypted in Python Packet.pack():
        // - DATA/NONE (0x00): Normal data
        // - LINKIDENTIFY (0xFB): Identity proof
        // - LINKCLOSE (0xFC): Graceful close
        // - LRRTT (0xFE): RTT measurement
        let encryptedContexts: [UInt8] = [
            PacketContext.NONE,
            PacketContext.LINKIDENTIFY,
            PacketContext.LINKCLOSE,
            PacketContext.LRRTT,
        ]

        XCTAssertTrue(encryptedContexts.contains(0x00))
        XCTAssertTrue(encryptedContexts.contains(0xFB))
        XCTAssertTrue(encryptedContexts.contains(0xFC))
        XCTAssertTrue(encryptedContexts.contains(0xFE))
    }

    /// Size constants match Python.
    func testSizeConstants() {
        XCTAssertEqual(MTU, 500)
        XCTAssertEqual(MDU, 464)
        XCTAssertEqual(ENCRYPTED_MDU, 383)
        XCTAssertEqual(TRUNCATED_HASH_LENGTH, 16)
        XCTAssertEqual(LinkConstants.LINK_MDU, 431)
        XCTAssertEqual(SIGNATURE_LENGTH, 64)
        XCTAssertEqual(PUBLIC_KEYS_LENGTH, 64)
        XCTAssertEqual(ANNOUNCE_RANDOM_HASH_LENGTH, 10)
        XCTAssertEqual(NAME_HASH_LENGTH, 10)
    }

    /// Header bit positions match Python Packet.py.
    func testHeaderBitPositions() {
        // IFAC flag = bit 7 = 0x80
        var h = PacketHeader(headerType: .header1, hasContext: false, hasIFAC: true,
                             transportType: .broadcast, destinationType: .single, packetType: .data, hopCount: 0)
        XCTAssertEqual(h.encode()[0] & 0x80, 0x80, "IFAC flag should be bit 7")

        // Header type = bit 6 = 0x40
        h = PacketHeader(headerType: .header2, hasContext: false,
                         transportType: .broadcast, destinationType: .single, packetType: .data, hopCount: 0)
        XCTAssertEqual(h.encode()[0] & 0x40, 0x40, "Header type should be bit 6")

        // Context flag = bit 5 = 0x20
        h = PacketHeader(headerType: .header1, hasContext: true,
                         transportType: .broadcast, destinationType: .single, packetType: .data, hopCount: 0)
        XCTAssertEqual(h.encode()[0] & 0x20, 0x20, "Context flag should be bit 5")

        // Transport type = bit 4 = 0x10
        h = PacketHeader(headerType: .header1, hasContext: false,
                         transportType: .transport, destinationType: .single, packetType: .data, hopCount: 0)
        XCTAssertEqual(h.encode()[0] & 0x10, 0x10, "Transport type should be bit 4")

        // Destination type = bits 3-2
        h = PacketHeader(headerType: .header1, hasContext: false,
                         transportType: .broadcast, destinationType: .plain, packetType: .data, hopCount: 0)
        XCTAssertEqual(h.encode()[0] & 0x0C, 0x08, "Plain dest type should be 0b10 in bits 3-2")

        h = PacketHeader(headerType: .header1, hasContext: false,
                         transportType: .broadcast, destinationType: .link, packetType: .data, hopCount: 0)
        XCTAssertEqual(h.encode()[0] & 0x0C, 0x0C, "Link dest type should be 0b11 in bits 3-2")

        // Packet type = bits 1-0
        h = PacketHeader(headerType: .header1, hasContext: false,
                         transportType: .broadcast, destinationType: .single, packetType: .proof, hopCount: 0)
        XCTAssertEqual(h.encode()[0] & 0x03, 0x03, "Proof packet type should be 0b11 in bits 1-0")
    }

    /// Link keep-alive magic bytes match Python.
    func testKeepaliveMagicBytes() {
        XCTAssertEqual(LinkConstants.KEEPALIVE_INITIATOR, 0xFF, "Initiator keepalive should be 0xFF")
        XCTAssertEqual(LinkConstants.KEEPALIVE_RESPONDER, 0xFE, "Responder keepalive should be 0xFE")
    }

    /// MDU formula: floor((mtu - 1 - 19 - 48) / 16) * 16 - 1
    func testMduFormula() {
        // Python: MDU = floor((MTU - IFAC_MIN_SIZE - HEADER_MINSIZE - TOKEN_OVERHEAD) / AES128_BLOCKSIZE) * AES128_BLOCKSIZE - 1
        // IFAC_MIN_SIZE=1, HEADER_MINSIZE=19 (2 header + 16 dest + 1 context), TOKEN_OVERHEAD=48, AES_BLOCKSIZE=16
        func mdu(for hwMtu: Int) -> Int {
            return ((hwMtu - 1 - 19 - 48) / 16) * 16 - 1
        }

        XCTAssertEqual(mdu(for: 500), 431, "MDU for MTU=500 should be 431")
        XCTAssertEqual(mdu(for: 262144), 262_063, "MDU for TCP MTU should be 262063")
        XCTAssertEqual(mdu(for: 1196), 1_119, "MDU for Auto MTU should be 1119")
        XCTAssertEqual(mdu(for: 508), 431, "MDU for BLE MTU should be 431")

        // Verify LINK_MDU constant matches the formula for default MTU
        XCTAssertEqual(LinkConstants.LINK_MDU, mdu(for: 500), "LINK_MDU should match formula for MTU=500")
    }
}
